### ISSUE TITLE
Requesting to Host it on Streamlit 

### ISSUE THREAD

**Issue by sharanreddy799** [Srikanth-Banda/PDF-Data-Analyzer#1]
Use streamlit and host it on the community cloud, too hassle to install and experience it :) .

**Comment by Srikanth-Banda** [comment]
Yes, it was already hosted on Streamlit. Please follow the demo(hyperlink) link available in the Readme.md to experience it. Let me know if there any suggestions.
Thanks!

**Comment by sharanreddy799** [comment]
Put it in "about" for better visibility 🤖

**Comment by Srikanth-Banda** [comment]
@sharanreddy799 Done, thanks! Yes it makes more sense to show in the 'about' section. Please experience and feel free to suggest any improvements.
